apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |
    [[runners]]
      name = "homelab-runner"
      url = "https://gitlab.com/"
      token = "glrt-t3_o_rjGD_Zch9dq3w5Gu5Z"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        service_account = "gitlab-runner"
        poll_timeout = 600
        image = "alpine:latest"
      [runners.cache]
        path = "/cache"
        shared = true

